# SIMDATA_ROOT_DIR = f'/media/kenta/Extreme SSD/dataset/carla_VR/'
# LOGDATE = '230724/'
# LOGDIR = 'log_115111/'

SIMDATA_ROOT_DIR = f'/media/kenta/ExtremePro/dataset/carla_VR/'
LOGDATE = f'230817/'
LOGDIR = f'log_131449_vr_celine-vr/'
POSE_DATA_ROOT_DIR = f'/media/kenta/ExtremePro/ego_exo/main/'
BIG_SEQUENCE = f'01_walk/'
SUB_SEQUENCE = f'001_walk/'
SUB_DIR = f'exo/cam01/images/'
